const studyData = {
    irregularVerbs: [
        { "Infinitivo": "be", "Pasado": "was, were", "Participio Pasado": "been", "Español": "ser, estar" },
        { "Infinitivo": "begin", "Pasado": "began", "Participio Pasado": "begun", "Español": "empezar" },
        { "Infinitivo": "buy", "Pasado": "bought", "Participio Pasado": "bought", "Español": "comprar" },
        { "Infinitivo": "choose", "Pasado": "chose", "Participio Pasado": "chosen", "Español": "elegir" },
        { "Infinitivo": "come", "Pasado": "came", "Participio Pasado": "come", "Español": "venir" },
        { "Infinitivo": "do", "Pasado": "did", "Participio Pasado": "done", "Español": "hacer" },
        { "Infinitivo": "drive", "Pasado": "drove", "Participio Pasado": "driven", "Español": "conducir" },
        { "Infinitivo": "drink", "Pasado": "drank", "Participio Pasado": "drunk", "Español": "beber" },
        { "Infinitivo": "eat", "Pasado": "ate", "Participio Pasado": "eaten", "Español": "comer" },
        { "Infinitivo": "feel", "Pasado": "felt", "Participio Pasado": "felt", "Español": "sentir" },
        { "Infinitivo": "find", "Pasado": "found", "Participio Pasado": "found", "Español": "encontrar" },
        { "Infinitivo": "get", "Pasado": "got", "Participio Pasado": "gotten", "Español": "obtener" },
        { "Infinitivo": "give", "Pasado": "gave", "Participio Pasado": "given", "Español": "dar" },
        { "Infinitivo": "go", "Pasado": "went", "Participio Pasado": "gone", "Español": "ir" },
        { "Infinitivo": "have", "Pasado": "had", "Participio Pasado": "had", "Español": "tener" },
        { "Infinitivo": "hear", "Pasado": "heard", "Participio Pasado": "heard", "Español": "oír" },
        { "Infinitivo": "know", "Pasado": "knew", "Participio Pasado": "known", "Español": "conocer" },
        { "Infinitivo": "learn", "Pasado": "learned/learnt", "Participio Pasado": "learned/learnt", "Español": "aprender" },
        { "Infinitivo": "leave", "Pasado": "left", "Participio Pasado": "left", "Español": "dejar, abandonar" },
        { "Infinitivo": "make", "Pasado": "made", "Participio Pasado": "made", "Español": "hacer" },
        { "Infinitivo": "read", "Pasado": "read", "Participio Pasado": "read", "Español": "leer" },
        { "Infinitivo": "run", "Pasado": "ran", "Participio Pasado": "run", "Español": "correr" },
        { "Infinitivo": "say", "Pasado": "said", "Participio Pasado": "said", "Español": "decir" },
        { "Infinitivo": "see", "Pasado": "saw", "Participio Pasado": "seen", "Español": "ver" },
        { "Infinitivo": "sing", "Pasado": "sang", "Participio Pasado": "sung", "Español": "cantar" },
        { "Infinitivo": "sit", "Pasado": "sat", "Participio Pasado": "sat", "Español": "sentarse" },
        { "Infinitivo": "sleep", "Pasado": "slept", "Participio Pasado": "slept", "Español": "dormir" },
        { "Infinitivo": "speak", "Pasado": "spoke", "Participio Pasado": "spoken", "Español": "hablar" },
        { "Infinitivo": "stand", "Pasado": "stood", "Participio Pasado": "stood", "Español": "estar de pie" },
        { "Infinitivo": "swim", "Pasado": "swam", "Participio Pasado": "swum", "Español": "nadar" },
        { "Infinitivo": "take", "Pasado": "took", "Participio Pasado": "taken", "Español": "tomar, coger" },
        { "Infinitivo": "tell", "Pasado": "told", "Participio Pasado": "told", "Español": "decir" },
        { "Infinitivo": "think", "Pasado": "thought", "Participio Pasado": "thought", "Español": "pensar" },
        { "Infinitivo": "win", "Pasado": "won", "Participio Pasado": "won", "Español": "ganar" },
        { "Infinitivo": "write", "Pasado": "wrote", "Participio Pasado": "written", "Español": "escribir" }
    ],
    simpleTimeAdverbs: [
        { "Adverbio": "Now", "Uso / Significado": "Ahora", "Ejemplo": "I am writing this sentence right now." },
        { "Adverbio": "Yesterday", "Uso / Significado": "Ayer", "Ejemplo": "I went to the park yesterday." },
        { "Adverbio": "Today", "Uso / Significado": "Hoy", "Ejemplo": "There’s a lot of sun today!" },
        { "Adverbio": "Tomorrow", "Uso / Significado": "Mañana", "Ejemplo": "We are leaving for our vacation tomorrow." },
        { "Adverbio": "Soon", "Uso / Significado": "Pronto", "Ejemplo": "The movie will start soon." },
        { "Adverbio": "Later", "Uso / Significado": "Más tarde", "Ejemplo": "We’ll eat later." },
        { "Adverbio": "Early", "Uso / Significado": "Temprano", "Ejemplo": "She always wakes up early." },
        { "Adverbio": "Late", "Uso / Significado": "Tarde", "Ejemplo": "I apologize for being late." },
        { "Adverbio": "Briefly", "Uso / Significado": "Brevemente", "Ejemplo": "She talked briefly and then stopped." },
        { "Adverbio": "Momentarily", "Uso / Significado": "Momentáneamente", "Ejemplo": "The sun disappeared momentarily, but then it came back." },
        { "Adverbio": "Forever", "Uso / Significado": "Para siempre", "Ejemplo": "I will love you forever." },
        { "Adverbio": "Temporarily", "Uso / Significado": "Temporalmente", "Ejemplo": "He is living with his friend temporarily." }
    ],
    prepositionAdverbs: [
        { "Estructura / Adverbio": "Before", "Uso / Significado": "Antes", "Ejemplo": "Please finish your homework before going to bed." },
        { "Estructura / Adverbio": "After", "Uso / Significado": "Después", "Ejemplo": "We go to the movies after finishing our work." },
        { "Estructura / Adverbio": "During", "Uso / Significado": "Durante", "Ejemplo": "I read a book during my lunch break." },
        { "Estructura / Adverbio": "Since", "Uso / Significado": "Desde", "Ejemplo": "I have been studying Spanish since last year." },
        { "Estructura / Adverbio": "Until", "Uso / Significado": "Hasta", "Ejemplo": "You can stay up until 10 p.m." },
        { "Estructura / Adverbio": "While", "Uso / Significado": "Mientras", "Ejemplo": "He was watching TV while eating dinner." },
        { "Estructura / Adverbio": "In (the morning)", "Uso / Significado": "En (la mañana)", "Ejemplo": "I have to go to the doctor in the morning." },
        { "Estructura / Adverbio": "On (Monday)", "Uso / Significado": "En (el lunes)", "Ejemplo": "I’ll be in London on Friday." },
        { "Estructura / Adverbio": "At (6 o’clock)", "Uso / Significado": "A (las 6 en punto)", "Ejemplo": "I’ll see you at 6 o’clock." },
        { "Estructura / Adverbio": "From…to…", "Uso / Significado": "Desde… hasta…", "Ejemplo": "The sports class lasts from 9 to 10 am." },
        { "Estructura / Adverbio": "For", "Uso / Significado": "Durante / Por", "Ejemplo": "She’s been waiting for him for 2 hours." }
    ],
    frequencyAdverbs: [
        { "Adverbio": "Always", "Uso / Significado": "Siempre", "Posición": "Antes del verbo (o después de \"to be\")", "Ejemplo": "He hasn’t always agreed with me." },
        { "Adverbio": "Usually", "Uso / Significado": "Usualmente", "Posición": "Antes del verbo", "Ejemplo": "They usually eat out on the weekend." },
        { "Adverbio": "Often", "Uso / Significado": "A menudo", "Posición": "Antes del verbo", "Ejemplo": "We don’t often go to bed late." },
        { "Adverbio": "Sometimes", "Uso / Significado": "A veces", "Posición": "Antes del verbo / al inicio o final", "Ejemplo": "Do you sometimes travel abroad?" },
        { "Adverbio": "Never", "Uso / Significado": "Nunca", "Posición": "Antes del verbo / después de \"to be\"", "Ejemplo": "I never go to the barber." },
        { "Adverbio": "Daily", "Uso / Significado": "A diario", "Posición": "Generalmente al final", "Ejemplo": "She exercises daily." },
        { "Adverbio": "Weekly", "Uso / Significado": "Semanalmente", "Posición": "Generalmente al final", "Ejemplo": "We meet weekly." },
        { "Adverbio": "Monthly", "Uso / Significado": "Mensualmente", "Posición": "Generalmente al final", "Ejemplo": "They pay the rent monthly." },
        { "Adverbio": "Yearly", "Uso / Significado": "Anualmente", "Posición": "Generalmente al final", "Ejemplo": "The event is held yearly." }
    ],
    regularVerbsId: [
        { "Base Form": "Accept", "Simple Past": "Accepted", "Past Participle": "Accepted", "Sound": "/ɪd/", "Spanish": "Aceptar" },
        { "Base Form": "Count", "Simple Past": "Counted", "Past Participle": "Counted", "Sound": "/ɪd/", "Spanish": "Contar" },
        { "Base Form": "Date", "Simple Past": "Dated", "Past Participle": "Dated", "Sound": "/ɪd/", "Spanish": "Citar" },
        { "Base Form": "End", "Simple Past": "Ended", "Past Participle": "Ended", "Sound": "/ɪd/", "Spanish": "Terminar" },
        { "Base Form": "Expect", "Simple Past": "Expected", "Past Participle": "Expected", "Sound": "/ɪd/", "Spanish": "Esperar" },
        { "Base Form": "Intend", "Simple Past": "Intended", "Past Participle": "Intended", "Sound": "/ɪd/", "Spanish": "Intentar" },
        { "Base Form": "Need", "Simple Past": "Needed", "Past Participle": "Needed", "Sound": "/ɪd/", "Spanish": "Necesitar" },
        { "Base Form": "Plant", "Simple Past": "Planted", "Past Participle": "Planted", "Sound": "/ɪd/", "Spanish": "Plantar" },
        { "Base Form": "Point", "Simple Past": "Pointed", "Past Participle": "Pointed", "Sound": "/ɪd/", "Spanish": "Señalar" },
        { "Base Form": "Rent", "Simple Past": "Rented", "Past Participle": "Rented", "Sound": "/ɪd/", "Spanish": "Rentar" },
        { "Base Form": "Repeat", "Simple Past": "Repeated", "Past Participle": "Repeated", "Sound": "/ɪd/", "Spanish": "Repetir" },
        { "Base Form": "Resist", "Simple Past": "Resisted", "Past Participle": "Resisted", "Sound": "/ɪd/", "Spanish": "Resistir" },
        { "Base Form": "Start", "Simple Past": "Started", "Past Participle": "Started", "Sound": "/ɪd/", "Spanish": "Empezar" },
        { "Base Form": "Visit", "Simple Past": "Visited", "Past Participle": "Visited", "Sound": "/ɪd/", "Spanish": "Visitar" },
        { "Base Form": "Wait", "Simple Past": "Waited", "Past Participle": "Waited", "Sound": "/ɪd/", "Spanish": "Esperar" },
        { "Base Form": "Want", "Simple Past": "Wanted", "Past Participle": "Wanted", "Sound": "/ɪd/", "Spanish": "Querer" }
    ],
    regularVerbsT: [
        { "Base Form": "Ask", "Simple Past": "Asked", "Past Participle": "Asked", "Sound": "/t/", "Spanish": "Preguntar" },
        { "Base Form": "Cook", "Simple Past": "Cooked", "Past Participle": "Cooked", "Sound": "/t/", "Spanish": "Cocinar" },
        { "Base Form": "Dance", "Simple Past": "Danced", "Past Participle": "Danced", "Sound": "/t/", "Spanish": "Bailar" },
        { "Base Form": "Dress", "Simple Past": "Dressed", "Past Participle": "Dressed", "Sound": "/t/", "Spanish": "Vestir" },
        { "Base Form": "Erase", "Simple Past": "Erased", "Past Participle": "Erased", "Sound": "/t/", "Spanish": "Borrar" },
        { "Base Form": "Finish", "Simple Past": "Finished", "Past Participle": "Finished", "Sound": "/t/", "Spanish": "Terminar" },
        { "Base Form": "Help", "Simple Past": "Helped", "Past Participle": "Helped", "Sound": "/t/", "Spanish": "Ayudar" },
        { "Base Form": "Jump", "Simple Past": "Jumped", "Past Participle": "Jumped", "Sound": "/t/", "Spanish": "Saltar" },
        { "Base Form": "Like", "Simple Past": "Liked", "Past Participle": "Liked", "Sound": "/t/", "Spanish": "Gustar" },
        { "Base Form": "Look", "Simple Past": "Looked", "Past Participle": "Looked", "Sound": "/t/", "Spanish": "Mirar" },
        { "Base Form": "Miss", "Simple Past": "Missed", "Past Participle": "Missed", "Sound": "/t/", "Spanish": "Extrañar" },
        { "Base Form": "Practice", "Simple Past": "Practiced", "Past Participle": "Practiced", "Sound": "/t/", "Spanish": "Practicar" },
        { "Base Form": "Push", "Simple Past": "Pushed", "Past Participle": "Pushed", "Sound": "/t/", "Spanish": "Empujar" },
        { "Base Form": "Shop", "Simple Past": "Shopped", "Past Participle": "Shopped", "Sound": "/t/", "Spanish": "Comprar" },
        { "Base Form": "Smoke", "Simple Past": "Smoked", "Past Participle": "Smoked", "Sound": "/t/", "Spanish": "Fumar" },
        { "Base Form": "Stop", "Simple Past": "Stopped", "Past Participle": "Stopped", "Sound": "/t/", "Spanish": "Detener" },
        { "Base Form": "Talk", "Simple Past": "Talked", "Past Participle": "Talked", "Sound": "/t/", "Spanish": "Hablar" },
        { "Base Form": "Use", "Simple Past": "Used", "Past Participle": "Used", "Sound": "/t/", "Spanish": "Usar" },
        { "Base Form": "Walk", "Simple Past": "Walked", "Past Participle": "Walked", "Sound": "/t/", "Spanish": "Caminar" },
        { "Base Form": "Wash", "Simple Past": "Washed", "Past Participle": "Washed", "Sound": "/t/", "Spanish": "Lavar" },
        { "Base Form": "Wish", "Simple Past": "Wished", "Past Participle": "Wished", "Sound": "/t/", "Spanish": "Desear" },
        { "Base Form": "Work", "Simple Past": "Worked", "Past Participle": "Worked", "Sound": "/t/", "Spanish": "Trabajar" }
    ],
    regularVerbsD: [
        { "Base Form": "Answer", "Simple Past": "Answered", "Past Participle": "Answered", "Sound": "/d/", "Spanish": "Responder" },
        { "Base Form": "Arrive", "Simple Past": "Arrived", "Past Participle": "Arrived", "Sound": "/d/", "Spanish": "Llegar" },
        { "Base Form": "Belong", "Simple Past": "Belonged", "Past Participle": "Belonged", "Sound": "/d/", "Spanish": "Pertenecer" },
        { "Base Form": "Change", "Simple Past": "Changed", "Past Participle": "Changed", "Sound": "/d/", "Spanish": "Cambiar" },
        { "Base Form": "Clean", "Simple Past": "Cleaned", "Past Participle": "Cleaned", "Sound": "/d/", "Spanish": "Limpiar" },
        { "Base Form": "Climb", "Simple Past": "Climbed", "Past Participle": "Climbed", "Sound": "/d/", "Spanish": "Escalar" },
        { "Base Form": "Close", "Simple Past": "Closed", "Past Participle": "Closed", "Sound": "/d/", "Spanish": "Cerrar" },
        { "Base Form": "Consider", "Simple Past": "Considered", "Past Participle": "Considered", "Sound": "/d/", "Spanish": "Considerar" },
        { "Base Form": "Dare", "Simple Past": "Dared", "Past Participle": "Dared", "Sound": "/d/", "Spanish": "Retar" },
        { "Base Form": "Deliver", "Simple Past": "Delivered", "Past Participle": "Delivered", "Sound": "/d/", "Spanish": "Entregar" },
        { "Base Form": "Enjoy", "Simple Past": "Enjoyed", "Past Participle": "Enjoyed", "Sound": "/d/", "Spanish": "Disfrutar" },
        { "Base Form": "Fill", "Simple Past": "Filled", "Past Participle": "Filled", "Sound": "/d/", "Spanish": "Llenar" },
        { "Base Form": "Follow", "Simple Past": "Followed", "Past Participle": "Followed", "Sound": "/d/", "Spanish": "Seguir" },
        { "Base Form": "Hurry", "Simple Past": "Hurried", "Past Participle": "Hurried", "Sound": "/d/", "Spanish": "Apurarse" },
        { "Base Form": "Learn", "Simple Past": "Learned", "Past Participle": "Learned", "Sound": "/d/", "Spanish": "Aprender" },
        { "Base Form": "Listen", "Simple Past": "Listened", "Past Participle": "Listened", "Sound": "/d/", "Spanish": "Escuchar" },
        { "Base Form": "Live", "Simple Past": "Lived", "Past Participle": "Lived", "Sound": "/d/", "Spanish": "Vivir" },
        { "Base Form": "Love", "Simple Past": "Loved", "Past Participle": "Loved", "Sound": "/d/", "Spanish": "Amar" },
        { "Base Form": "Name", "Simple Past": "Named", "Past Participle": "Named", "Sound": "/d/", "Spanish": "Nombrar" },
        { "Base Form": "Open", "Simple Past": "Opened", "Past Participle": "Opened", "Sound": "/d/", "Spanish": "Abrir" },
        { "Base Form": "Order", "Simple Past": "Ordered", "Past Participle": "Ordered", "Sound": "/d/", "Spanish": "Ordenar" },
        { "Base Form": "Plan", "Simple Past": "Planned", "Past Participle": "Planned", "Sound": "/d/", "Spanish": "Planear" },
        { "Base Form": "Play", "Simple Past": "Played", "Past Participle": "Played", "Sound": "/d/", "Spanish": "Jugar" },
        { "Base Form": "Rain", "Simple Past": "Rained", "Past Participle": "Rained", "Sound": "/d/", "Spanish": "Llover" },
        { "Base Form": "Remember", "Simple Past": "Remembered", "Past Participle": "Remembered", "Sound": "/d/", "Spanish": "Recordar" },
        { "Base Form": "Show", "Simple Past": "Showed", "Past Participle": "Showed", "Sound": "/d/", "Spanish": "Mostrar" },
        { "Base Form": "Stay", "Simple Past": "Stayed", "Past Participle": "Stayed", "Sound": "/d/", "Spanish": "Permanecer" },
        { "Base Form": "Study", "Simple Past": "Studied", "Past Participle": "Studied", "Sound": "/d/", "Spanish": "Estudiar" },
        { "Base Form": "Travel", "Simple Past": "Traveled", "Past Participle": "Traveled", "Sound": "/d/", "Spanish": "Viajar" },
        { "Base Form": "Try", "Simple Past": "Tried", "Past Participle": "Tried", "Sound": "/d/", "Spanish": "Intentar" },
        { "Base Form": "Turn", "Simple Past": "Turned", "Past Participle": "Turned", "Sound": "/d/", "Spanish": "Girar" }
    ],
    connectorsCause: [
        { "Conector": "because", "Significado": "porque", "Ejemplo": "I stayed home because it was raining." },
        { "Conector": "since", "Significado": "ya que, puesto que", "Ejemplo": "Since you’re here, let’s start the meeting." },
        { "Conector": "as", "Significado": "como, dado que", "Ejemplo": "As it was late, we decided to leave." },
        { "Conector": "for", "Significado": "porque (formal)", "Ejemplo": "He must be hungry, for he hasn’t eaten all day." }
    ],
    connectorsResult: [
        { "Conector": "so", "Significado": "así que", "Ejemplo": "It was raining, so we stayed inside." },
        { "Conector": "therefore", "Significado": "por lo tanto", "Ejemplo": "He was ill, therefore he couldn’t come." },
        { "Conector": "thus", "Significado": "así, de este modo (formal)", "Ejemplo": "She worked hard, thus she succeeded." },
        { "Conector": "hence", "Significado": "de ahí, por eso (formal)", "Ejemplo": "He didn’t study, hence his bad grades." }
    ],
    connectorsContrast: [
        { "Conector": "but", "Significado": "pero", "Ejemplo": "I like coffee, but I prefer tea." },
        { "Conector": "however", "Significado": "sin embargo", "Ejemplo": "It was cold. However, we went swimming." },
        { "Conector": "although / though", "Significado": "aunque", "Ejemplo": "Although it was late, they kept working." },
        { "Conector": "even though", "Significado": "aunque (enfatizado)", "Ejemplo": "Even though he was tired, he continued." },
        { "Conector": "while / whereas", "Significado": "mientras que", "Ejemplo": "She likes jazz, while I prefer rock." },
        { "Conector": "yet", "Significado": "sin embargo", "Ejemplo": "It’s simple, yet effective." }
    ],
    connectorsAddition: [
        { "Conector": "and", "Significado": "y", "Ejemplo": "She bought apples and oranges." },
        { "Conector": "also", "Significado": "también", "Ejemplo": "He is smart and also kind." },
        { "Conector": "too", "Significado": "también (al final)", "Ejemplo": "I like pizza too." },
        { "Conector": "as well", "Significado": "también", "Ejemplo": "She plays the piano as well." },
        { "Conector": "in addition", "Significado": "además", "Ejemplo": "In addition, we need more volunteers." },
        { "Conector": "moreover / furthermore", "Significado": "además (formal)", "Ejemplo": "The plan is simple. Moreover, it’s cheap." }
    ],
    connectorsTime: [
        { "Conector": "when", "Significado": "cuando", "Ejemplo": "I called you when I arrived." },
        { "Conector": "while", "Significado": "mientras", "Ejemplo": "She was cooking while I was cleaning." },
        { "Conector": "before", "Significado": "antes de que", "Ejemplo": "Wash your hands before you eat." },
        { "Conector": "after", "Significado": "después de que", "Ejemplo": "I’ll call you after the meeting." },
        { "Conector": "then", "Significado": "luego", "Ejemplo": "First we went shopping, then we had lunch." },
        { "Conector": "next", "Significado": "a continuación", "Ejemplo": "Next, you should press the button." },
        { "Conector": "finally", "Significado": "finalmente", "Ejemplo": "Finally, we reached the hotel." }
    ],
    connectorsCondition: [
        { "Conector": "if", "Significado": "si", "Ejemplo": "If it rains, we’ll stay home." },
        { "Conector": "unless", "Significado": "a menos que", "Ejemplo": "You can’t go out unless you finish homework." },
        { "Conector": "as long as", "Significado": "siempre que", "Ejemplo": "You can borrow it as long as you return it." },
        { "Conector": "provided that", "Significado": "con tal de que", "Ejemplo": "You can come, provided that you behave." }
    ],
    connectorsComparison: [
        { "Conector": "like", "Significado": "como", "Ejemplo": "He runs like a professional." },
        { "Conector": "as…as", "Significado": "tan…como", "Ejemplo": "She is as tall as her brother." },
        { "Conector": "than", "Significado": "que (comparativo)", "Ejemplo": "This book is better than that one." }
    ],
    daysOfWeek: [
        { "Inglés": "Monday", "Español": "Lunes" },
        { "Inglés": "Tuesday", "Español": "Martes" },
        { "Inglés": "Wednesday", "Español": "Miércoles" },
        { "Inglés": "Thursday", "Español": "Jueves" },
        { "Inglés": "Friday", "Español": "Viernes" },
        { "Inglés": "Saturday", "Español": "Sábado" },
        { "Inglés": "Sunday", "Español": "Domingo" }
    ],
    months: [
        { "Inglés": "January", "Español": "Enero" },
        { "Inglés": "February", "Español": "Febrero" },
        { "Inglés": "March", "Español": "Marzo" },
        { "Inglés": "April", "Español": "Abril" },
        { "Inglés": "May", "Español": "Mayo" },
        { "Inglés": "June", "Español": "Junio" },
        { "Inglés": "July", "Español": "Julio" },
        { "Inglés": "August", "Español": "Agosto" },
        { "Inglés": "September", "Español": "Septiembre" },
        { "Inglés": "October", "Español": "Octubre" },
        { "Inglés": "November", "Español": "Noviembre" },
        { "Inglés": "December", "Español": "Diciembre" }
    ],
    numbers: [
        { "Inglés": "One", "Español": "Uno", "Número": "1" },
        { "Inglés": "Two", "Español": "Dos", "Número": "2" },
        { "Inglés": "Three", "Español": "Tres", "Número": "3" },
        { "Inglés": "Four", "Español": "Cuatro", "Número": "4" },
        { "Inglés": "Five", "Español": "Cinco", "Número": "5" },
        { "Inglés": "Six", "Español": "Seis", "Número": "6" },
        { "Inglés": "Seven", "Español": "Siete", "Número": "7" },
        { "Inglés": "Eight", "Español": "Ocho", "Número": "8" },
        { "Inglés": "Nine", "Español": "Nueve", "Número": "9" },
        { "Inglés": "Ten", "Español": "Diez", "Número": "10" },
        { "Inglés": "Eleven", "Español": "Once", "Número": "11" },
        { "Inglés": "Twelve", "Español": "Doce", "Número": "12" },
        { "Inglés": "Thirteen", "Español": "Trece", "Número": "13" },
        { "Inglés": "Fourteen", "Español": "Catorce", "Número": "14" },
        { "Inglés": "Fifteen", "Español": "Quince", "Número": "15" },
        { "Inglés": "Sixteen", "Español": "Dieciséis", "Número": "16" },
        { "Inglés": "Seventeen", "Español": "Diecisiete", "Número": "17" },
        { "Inglés": "Eighteen", "Español": "Dieciocho", "Número": "18" },
        { "Inglés": "Nineteen", "Español": "Diecinueve", "Número": "19" },
        { "Inglés": "Twenty", "Español": "Veinte", "Número": "20" },
        { "Inglés": "Thirty", "Español": "Treinta", "Número": "30" },
        { "Inglés": "Forty", "Español": "Cuarenta", "Número": "40" },
        { "Inglés": "Fifty", "Español": "Cincuenta", "Número": "50" },
        { "Inglés": "Sixty", "Español": "Sesenta", "Número": "60" },
        { "Inglés": "Seventy", "Español": "Setenta", "Número": "70" },
        { "Inglés": "Eighty", "Español": "Ochenta", "Número": "80" },
        { "Inglés": "Ninety", "Español": "Noventa", "Número": "90" },
        { "Inglés": "One hundred", "Español": "Cien", "Número": "100" }
    ],
    houseParts: [
        { "Inglés": "Living room", "Español": "Sala de estar" },
        { "Inglés": "Dining room", "Español": "Comedor" },
        { "Inglés": "Kitchen", "Español": "Cocina" },
        { "Inglés": "Bedroom", "Español": "Dormitorio" },
        { "Inglés": "Bathroom", "Español": "Baño" },
        { "Inglés": "Garage", "Español": "Garaje" },
        { "Inglés": "Garden", "Español": "Jardín" },
        { "Inglés": "Roof", "Español": "Techo" },
        { "Inglés": "Window", "Español": "Ventana" },
        { "Inglés": "Door", "Español": "Puerta" }
    ],
    animals: [
        { "Inglés": "Dog", "Español": "Perro" },
        { "Inglés": "Cat", "Español": "Gato" },
        { "Inglés": "Horse", "Español": "Caballo" },
        { "Inglés": "Cow", "Español": "Vaca" },
        { "Inglés": "Sheep", "Español": "Oveja" },
        { "Inglés": "Lion", "Español": "León" },
        { "Inglés": "Tiger", "Español": "Tigre" },
        { "Inglés": "Bear", "Español": "Oso" },
        { "Inglés": "Fish", "Español": "Pez" },
        { "Inglés": "Bird", "Español": "Pájaro" }
    ],
    dailyRoutine: [
        { "Inglés": "Wake up", "Español": "Despertarse" },
        { "Inglés": "Get up", "Español": "Levantarse" },
        { "Inglés": "Take a shower", "Español": "Darse una ducha" },
        { "Inglés": "Get dressed", "Español": "Vestirse" },
        { "Inglés": "Have breakfast", "Español": "Desayunar" },
        { "Inglés": "Go to work/school", "Español": "Ir al trabajo/escuela" },
        { "Inglés": "Have lunch", "Español": "Almorzar" },
        { "Inglés": "Finish work/school", "Español": "Terminar el trabajo/la escuela" },
        { "Inglés": "Go home", "Español": "Ir a casa" },
        { "Inglés": "Have dinner", "Español": "Cenar" },
        { "Inglés": "Watch TV", "Español": "Ver la televisión" },
        { "Inglés": "Go to bed", "Español": "Acostarse" }
    ]
};
